# permissions for end users to view lens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: len-viewer-role
rules:
- apiGroups:
  - stable.example.com.my.domain
  resources:
  - lens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stable.example.com.my.domain
  resources:
  - lens/status
  verbs:
  - get
