# permissions for end users to edit lens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: len-editor-role
rules:
- apiGroups:
  - stable.example.com.my.domain
  resources:
  - lens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.example.com.my.domain
  resources:
  - lens/status
  verbs:
  - get
